server:
  port: 8506
#  profiles:
#    active: native
spring:
  cloud:
    config:
      server:
#        encrypt:
#          enabled: false #should in bootstrap.properties
        git:
          uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls
          #username: username
          #password: password
          search-paths:
            - 'station*'
          repos:
             local:
                pattern: '*/local'
                uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-local
                search-paths:
                 - 'station*'
  security:
#    basic:
#      enabled: false #doesn't work in Spring book 2
    user:
      name: pluralsight
      password: pluralsight