server:
  port: 8506
#  profiles:
#    active: native
spring:
  cloud:
    config:
      server:
        git:
          uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls
          #username: username
          #password: password
          search-paths:
            - 'station*'
          repos:
             local:
                pattern: '*/local'
                uri: https://github.com/rseroter/pluralsight-spring-cloudconfig-wa-tolls-local
                search-paths:
                 - 'station*'
